### PR TITLE
Added Cat as copy of Beagle; added Cattle as copy of Minipig; no species-specific values set yet

### PR DESCRIPTION
**Pull request by Yuri05**
@msevestre 
in the first step, I just created Cat and Cattle as a copy of Beagle and Minipig respectively.
No species-specific parameters are set yet - those will be set in the next iteration based on the values uploaded in https://github.com/Open-Systems-Pharmacology/Forum/discussions/953

Also added an SQL script for copying an (animal) species

### CODE REVIEW

**Comment by msevestre** [comment]
COOL!

**Comment by msevestre** [comment]
but the build is kaputt

**Comment by msevestre** [comment]
lol

```
PKSim.IntegrationTests.When_checking_the_changes_in_the_database_for_version_7_1_0.should_remove_species_cattle_and_cat
  Expected: False
  But was:  True
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeEqualTo[T](T actual, T expected, String message)
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeFalse(Boolean item, String message)
   at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldNotContain[T](IEnumerable`1 items, T[] itemsToFind)
   at PKSim.IntegrationTests.When_checking_the_changes_in_the_database_for_version_7_1_0.should_remove_species_cattle_and_cat() in C:\projects\pk-sim-g4na9\tests\PKSim.Tests\IntegrationTests\DatabaseUpdateSpecs.cs:line 286
```

**Comment by Yuri05** [comment]
obviously :) removed the test

**Pull request merged**
